### LECCIÓN I: CATEGORÍA Y TIPO DE DATOS

**Heber Hernández Guerra, Ingeniero Civil de Minas, Relator Curso**  

Contacto: heber@nubeminera.cl |https://github.com/heberallin |https://www.facebook.com/heberbluff

En el presente notebook conoceremos la forma de crear matrices en Python a través de un ejemplo relacionado con la estimación de Kriging Simple.

**Supondremos una estimación, donde tenemos la siguiente información:**

* Ley 1: 0.5 ppm Au
* Ley 2: 0.9 ppm Au
* Ley media global = 1.2 ppm Au

**Sistema de kriging:**

2 **λ1** + 1.4 **λ2** = 0.36

1.4 **λ1** + 2 **λ2** = 0.42

**Calcular Z**

In [1]:
import numpy as np # Biblioteca de funciones matematicas de alto nivel, imprescindible en analisis de datos. 

In [40]:
ma = np.array([[2, 1.4], [1.4, 2]]) # Matriz A de covarianzas entre los datos conocidos

In [41]:
ma

array([[2. , 1.4],
       [1.4, 2. ]])

In [55]:
type(ma) # tipo de dato

numpy.ndarray

In [50]:
ma.ndim # numero de dimensiones de la matriz

2

In [53]:
ma.shape #Para ver la forma 2 filas 2 columna

(2, 2)

In [43]:
mb = np.array([[0.36], [0.42]]) # Matriz B de covarianzas entre datos conocidos y punto a estimar

In [44]:
mb

array([[0.36],
       [0.42]])

In [45]:
ms = np.linalg.solve(ma, mb) #función para resover matriz incognita 

In [46]:
ms

array([[0.06470588],
       [0.16470588]])

In [71]:
lambda_1 = float(ms[0])

In [72]:
lambda_2 = float(ms[1])

In [73]:
lambda_3 = (1-lambda_1 - lambda_2)

In [74]:
lambda_1 + lambda_2 + lambda_3 # Condición de insesgo lineal

1.0

In [76]:
z = ((lambda_1 * 0.5) + (lambda_2 * 0.9) + (lambda_3 * 1.2))
print(z, "ppm Au")

1.1052941176470588 ppm Au
